```{r init echo=FALSE, message=FALSE}
library(caret)
library(dplyr)
library(tidyr)
set.seed(2015)

if(!(exists("dat.full")))dat.full<-read.csv("pml-training.csv",header=TRUE)
dat<-dat.full
knitr::opts_chunk$set(echo=TRUE,warning=FALSE,message=FALSE) #option set for all md code 
```


Data selection and cleanup
============================================================================

```{r pruning, echo=TRUE}
#The original data contain user identifiers. Users probably have distinctive movement patterns, and the classes are not evenly distributed over users, possibly allowing user name to become a spurious predictor effective in the training data only. Training data was anonymized (somewhat) by removing user_name, new_window, and num_window, dropping cvtd_timestamps and converting raw timestamps to relative timestamps.
cleandf<-function(dat){
dat.clean<-as.data.frame(dat%>%
  group_by(user_name)%>%
  mutate(raw_timestamp_part_1=raw_timestamp_part_1-min(raw_timestamp_part_1))%>%
  ungroup()%>%
  dplyr::select(-X,-user_name, -cvtd_timestamp,-new_window,-num_window,-raw_timestamp_part_2) )#dplyr identifier needed on select to avoid clashes with MASS

#There are some variables that look like they're intended to be numeric, but rendered as factors due to the presence of #DIV0 markers or empty strings. Try to convert them, failures to parse as a number convert to NA.
for(name in names(dat.clean)){
  if(class(dat.clean[,name])=="factor"&&name!="classe")dat.clean[,name]<-as.numeric(as.character(dat.clean[,name]))
  #remove variables with many NA values
  if(sum(is.na(dat.clean[,name]))>=nrow(dat.clean)/4)dat.clean<-dat.clean[,-which(names(dat.clean)==name)]
}


#Also remove uninformative columns (low variation).
if(length(nearZeroVar(dat.clean)>0))dat.good<-dat.clean[,-nearZeroVar(dat.clean)]#'if' necessary, selecting -<empty vector> cols selects no cols not all of them. :-(
return(dat.clean)
}

dat.full<-cleandf(dat.full)

#fitting to the full dataset is SLOW. My laptop can only just handle these tiny subsamples
dat.clean<-sample_n(dat.full,200)
dat.minitest<-sample_n(dat.full,200)
```

Classifier
====================================================================================
```{r classifier}
#also tried lda, it's faster but not as accurate.
fitrf<-train(classe~.,method="rf",preProcess=c("center","scale"),data=dat.clean)
```

```{r checking}
preds<-predict(fitrf,newdata=dat.minitest)

dat.minitest$hardcase<-as.factor(as.character(preds!=dat.minitest$classe))#convert to factor to allow 'train' to run smoothly. Via character for readability.

sobspotter<-train(hardcase~.,method="rf",preProcess=c("center","scale"),data=dat.minitest)

hardcases<-predict(sobspotter,newdata=dat.full)

sobs<-sample_n(dat.full[hardcases=="TRUE",],200)
sobhandler<-train(classe~.,method="rf",preProcess=c("center","scale"),data=sobs)
```

```{r test}
dat.test<-read.csv("pml-testing.csv")
dat.test<-sample_n(dat.full,500) #cleandf(dat.test)

easypred<-as.character(predict(fitrf,newdata=dat.test))
hardpred<-as.character(predict(sobhandler,newdata=dat.test))
usehard<-as.character(predict(sobspotter,newdata=dat.test))

dat.test$prediction<-ifelse(usehard=="TRUE",hardpred,easypred)
dat.test$accurate<-dat.test$prediction==dat.test$classe
```

Data citation
=====================================================
Velloso, E.; Bulling, A.; Gellersen, H.; Ugulino, W.; Fuks, H. Qualitative Activity Recognition of Weight Lifting Exercises. Proceedings of 4th International Conference in Cooperation with SIGCHI (Augmented Human '13) . Stuttgart, Germany: ACM SIGCHI, 2013. 
